# Generated by Django 4.1.1 on 2022-09-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_stamp']},
        ),
    ]
